name: Check Added Submodules

on:
  pull_request:
    branches:
      - main

jobs:
  style:
    name: Run StyLua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout LLS-Addons
        with:
          submodules: false

      - name: Fetch Base Branch
        run: |
          # Fetch all history for the base branch and PR head
          git fetch origin ${{ github.base_ref }} --depth=1
          git fetch origin ${{ github.head_ref }} --depth=1

      - name: Detect Added Submodules
        run: |
          BASE_REF=${{ github.event.pull_request.base.sha }}
          HEAD_REF=${{ github.event.pull_request.head.sha }}

          ADDED_SUBMODULES=$(git diff --submodule ${BASE_REF}..${HEAD_REF} | grep '^Submodule' | awk '{ print $2 }')
          echo "Added submodules: $ADDED_SUBMODULES"
          echo "ADDED_SUBMODULES=$ADDED_SUBMODULES" >> $GITHUB_ENV

      - name: Fetch submodules
        run: |
          for submodule in $ADDED_SUBMODULES; do
              echo "Getting submodule: $submodule"
              git submodule update --init --recursive $submodule
            done

      - uses: JohnnyMorganz/stylua-action@v2.0.0
        name: Run StyLua
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check addons
